name: build project
env:
  PROJECT_FILE: Source/Obliterator/Obliterator.csproj
  PROJECT_DIR: mod
  PROJECT_NAME: obliterator
  APP_ID: 294100
  ITEM_ID: 2558216591
  VERSION: 1.0.0
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Add Krafs.Rimworld.Ref package
      run: dotnet add ${{ env.PROJECT_DIR }}/${{ env.PROJECT_FILE }} package Krafs.Rimworld.Ref --version 1.3.3071 
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_DIR }}/${{ env.PROJECT_FILE }} 
      
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_DIR }}/${{ env.PROJECT_FILE }}

    - name: Upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-${{ env.VERSION }}
        path: |
          ${{ github.workspace }}/${{ env.PROJECT_DIR }}/
          !${{ github.workspace }}${{ env.PROJECT_DIR }}/Source